### ISSUE TITLE
Doesn't highlight an error

### ISSUE THREAD

**Issue by pawelgrzybek** [skovhus/SublimeLinter-contrib-sass-lint#7]
Hello guys. Amazing plugin, just started using it few days ago as a replacement for ruby scss-lint. I just found same minor inconsistency between ST and CLI.

This is my CSS bit.

``` css
.mostrec__image {
    transform: scale(1..05);
    opacity: 1;
}
```

This is CLI output.

```
src/sass/modules/_mostrec.scss
Error: error reading values after 1
        on line 29 of src/sass/modules/_mostrec.scss
>>       transform: scale(1..05);
   -----------------------^
```

Sublime text doesn't highlight anything on place of double periods.
My config file is here: https://github.com/pawelgrzybek/dotfiles/blob/master/.sass-lint.yml
